### ISSUE TITLE
Branching doesnt seem to draw properly.

### ISSUE THREAD

**Issue by kylechase** [Mustry-Solutions/ignition-branching-module#1]
Here is my data
```
[
  {
    "color": "#00ff00",
    "name": "node1",
    "id": 1,
    "nextId": [
      2,
      3
    ],
    "fill": false,
    "category": 0
  },
  {
    "nextId": [
      4
    ],
    "color": "#ff0000",
    "name": "node2",
    "id": 2,
    "category": 0,
    "fill": false
  },
  {
    "nextId": [
      5
    ],
    "color": "#ff0000",
    "name": "node3",
    "id": 3,
    "category": 2,
    "fill": false
  },
  {
    "nextId": [
      5
    ],
    "color": "#ff0000",
    "name": "node4",
    "id": 4,
    "category": 0,
    "fill": false
  },
  {
    "nextId": [],
    "color": "#ff0000",
    "name": "node5",
    "id": 5,
    "category": 0,
    "fill": false
  }
]
```

It is currently drawing
![image](https://user-images.githubusercontent.com/4741043/231184577-d528e8d1-b215-4308-9f8b-075a1ecf7c8d.png)

I am expecting it would draw something like
![image](https://user-images.githubusercontent.com/4741043/231185253-65679f20-21d1-48bb-a7dd-26125475657e.png)

**Comment by tilouage** [comment]
Hello, thank you for using our component and thank you for bringing this issue to light. I am aware of this issue, it is caused because the connection of 2 nodes is always done at 50% between 2 nodes (so the connection is drawn behind the node).
I hope in a future release I could fix this issue.

**Comment by tilouage** [comment]
Hello @kylechase, in the latest release this issue has been solved (https://github.com/Mustry-Solutions/ignition-branching-module/releases/tag/v1.0.2). Now it dynamically looks what possible paths can be drawn.
Your example now looks like this:
![Screenshot 2023-05-03 103247](https://user-images.githubusercontent.com/74241667/235868427-1d07c777-be0a-4e73-b289-0a660c41de59.png)

It might also occur that a path needs to be drawn sooner, like in this example:
![Screenshot 2023-05-03 103342](https://user-images.githubusercontent.com/74241667/235868575-fba67a52-f0e0-4a77-9577-e2f82eb53781.png)

Lastly when no path is available a diagonal path is drawn.
![Screenshot 2023-05-03 103443](https://user-images.githubusercontent.com/74241667/235868699-c0fdf3a7-994d-4f78-a767-79ed096a5d1b.png)

I am aware that this is not the most sexy looking line that you might have seen, but I hope to change the way this looks in a future release.
